inputs:
  port:
    description: "The TCP/IP port number"
    default: '7001'
  envirnoment:
    description: "The TCP/IP port number"
    default: 'DEV'

runs:
  using: "composite"
  steps:
  - name: Print output
    run: echo Deployment to ${{ inputs.enviroment }} has started...

  - name: Checkout python-greetings repository
    uses: actions/checkout@v3.5.2
    with:
      repository: "mtararujs/python-greetings"
      path: "python-greetings"
      ref: "4e911440a9886c7c26ccbb4eb55f0bc2a5067b51"
  
  - name: Delete previous service
    run: cmd /c "pm2 delete greetings-app-dev & set \"errorlevel=0\""

  - name: Start new service
    run: cmd /c "pm2 start app.py --name greetings-app-${{ inputs.enviroment }} -- --${{ inputs.port }}"
